### ISSUE TITLE
Implement stricter input

### ISSUE THREAD

**Issue by nemesisdesign** [ninuxorg/netdiff#40]
The first argument (`data`) of each parser can represent many things:
- topology data
- a file path
- a URL

Unfortunately this can cause different type of issues, including security issues in which an attacker can access a file on a remote machine that uses _netdiff_ to accept **network topology** data through a `POST` request.

It would be better to implement stricter initialization arguments, eg: `data`, `path`, `url`.

**Comment by acoul** [comment]
unfortunately this change breaks  https://github.com/coxley/aspath_graph which I use to convert BGP txt dump to json

**Comment by nemesisdesign** [comment]
@acoul: upgrading client code is very easy, it just requires to specify if the input is a url, file or data.

See the changes in the tests to understand what I mean: https://github.com/ninuxorg/netdiff/commit/aa810031cceba2e6d322ded91f3f8fd1bfb2dea4

One question, I don't understand what do you mean for breaking [aspath_graph](https://github.com/coxley/aspath_graph), I thought that package did not use netdiff.

**Comment by acoul** [comment]
this is the error I am getting:

> [ERROR 2017-09-21 15:06:26,309] module: contextmanagers, process: 20937, thread: -1213524224
Failed to perform update on <Topology: AWMN - NetJSON NetworkGraph>
Traceback (most recent call last):
  File "/awmn/.local/lib/python3.4/site-packages/django_netjsongraph/contextmanagers.py", line 10, in log_failure
    yield
  File "/awmn/.local/lib/python3.4/site-packages/django_netjsongraph/base/topology.py", line 305, in update_all
    topology.update()
  File "/awmn/.local/lib/python3.4/site-packages/django_netjsongraph/base/topology.py", line 185, in update
    diff = self.diff(data)
  File "/awmn/.local/lib/python3.4/site-packages/django_netjsongraph/base/topology.py", line 133, in diff
    latest = self.get_topology_data(data)
  File "/awmn/.local/lib/python3.4/site-packages/django_netjsongraph/base/topology.py", line 114, in get_topology_data
    latest = self.parser_class(data, timeout=TIMEOUT)
  File "/awmn/.local/lib/python3.4/site-packages/netdiff/parsers/base.py", line 56, in __init__
    self.original_data = self.to_python(data)
  File "/awmn/.local/lib/python3.4/site-packages/netdiff/parsers/base.py", line 89, in to_python
    raise ConversionException('Could not recognize format', data=data)
netdiff.exceptions.ConversionException: Could not recognize format

**Comment by acoul** [comment]
I am not sure if this issue should be reported here or @ https://github.com/netjson/django-netjsongraph

FWIW I was able to get going again by reverting this: https://github.com/ninuxorg/netdiff/commit/42484a9ce5945bd91ac1985393a39f90ec7cb43d

I simply updated the .local/lib/python3.4/site-packages/netdiff/parsers/base.py by hand

**Comment by nemesisdesign** [comment]
If you don't want issues, stick to django-netjsongraph 0.3.4 and netdiff 0.4.8.

**Comment by acoul** [comment]
the above netdiff 0.5.0 revert actually produces a 0.4.8 IMHO

I was just following this: https://github.com/netjson/django-netjsongraph/blob/master/requirements.txt

> netdiff>=0.5.0,<=6.0

**Comment by nemesisdesign** [comment]
yes, is correct

**Comment by acoul** [comment]
this was my bad: https://github.com/netjson/django-netjsongraph/issues/57

all seem to work as they should. sorry for the noise.

**Comment by nemesisdesign** [comment]
@acoul: thx for the update!
