### ISSUE TITLE
netdiff and jsoninfo plugin OLSRD

### ISSUE THREAD

**Issue by sp2ong** [ninuxorg/netdiff#41]
Hi,

I have try use netdiff to create netjsonGraph from my local network base on OLSRD 1 (version olsrd v0.9)
I have create simple file with following:

import os
import six
import networkx

from netdiff import OlsrParser
from netdiff import diff

olsr = OlsrParser('telnet://127.0.0.1:9090')
......

when I have run script I have following errors:
Traceback (most recent call last):
  File "pmk.py", line 9, in <module>
    olsr = OlsrParser('telnet://127.0.0.1:9090')
  File "/data/src/netdiff-master/netdiff/parsers/base.py", line 46, in __init__
    self.original_data = self.to_python(data)
  File "/data/src/netdiff-master/netdiff/parsers/olsr.py", line 20, in to_python
    return self._txtinfo_to_jsoninfo(e.data)
  File "/data/src/netdiff-master/netdiff/parsers/olsr.py", line 89, in _txtinfo_to_jsoninfo
    raise ParserError('Unrecognized format')

But when I switch to use textinfo plugin on port 2006 I have result with create output ready to use with netjson.js

How to create script to get date via jsoninfo plugin istead textinfo plugin ????

**Comment by nemesisdesign** [comment]
@sp2ong there might be a case with the jsoninfo output which is not handled well.

Could you paste the output here? If the network info is sensitive, could you send it to me via email?

**Comment by nemesisdesign** [comment]
Sorry @sp2ong, could you try to enable http headers and use HTTP instead?

Like indicated here:
https://github.com/ninuxorg/netdiff#connectionerror-badstatusline

**Comment by sp2ong** [comment]
Ok Federico,

Yes I have enabled http headers but don't help to get info.
Ok I will be send via email my output form jsoninfo on google+ contact please check

Best regards

Waldek

**Comment by nemesisdesign** [comment]
Send it at nemesis at ninux dot org, I'll check tomorrow

**Comment by sp2ong** [comment]
Ok I have send .

Thank you for help

**Comment by sp2ong** [comment]
I have one question how is add fields like

label: giuseppe
posizione-zona: Ninux.org Sicilia
name: Claud43

http://ninux-graph.netjson.org/topology/0be4cf60-99b8-4fde-a8fe-765cbb43d6b9/

I can see this in olsrd.conf possible but I have see that in  in souce json file in above example in "properties":

{
            "id": "172.31.90.40",
            "label": "claud43",
            "properties": {
                "posizione-zona": "Ninux.org Sicilia",
                "name": "Claud43",
}

**Comment by nemesisdesign** [comment]
That web application is a different project: [django-netjsongraph topology collector & visualizer](https://github.com/interop-dev/django-netjsongraph), are you using it?
It allows adding any additional property in JSON format. That instance automatically takes some information from the ninux whois service.

**Comment by nemesisdesign** [comment]
@sp2ong you are using the new olsrd1 netjson plugin, which has a few issues which the author is working on to fix. Try using the jsoninfo plugin instead: http://www.olsr.org/?q=jsoninfo_plugin

**Comment by sp2ong** [comment]
Hi

Yes I have use latest version olsrd pre-0.9.1 with netjson plugin but netjson plugin use other access port not 9090 where I have defined port for jsoninfo plugin.

OK I have switch to olsrd v0.9.0.3  and try again use netdif with jsoninfo plugin but I have the same result:

Traceback (most recent call last):
  File "pmk.py", line 9, in <module>
    olsr = OlsrParser('telnet://127.0.0.1:9090')
  File "/data/src/netdiff-master/netdiff/parsers/base.py", line 46, in __init__
    self.original_data = self.to_python(data)
  File "/data/src/netdiff-master/netdiff/parsers/olsr.py", line 20, in to_python
    return self._txtinfo_to_jsoninfo(e.data)
  File "/data/src/netdiff-master/netdiff/parsers/olsr.py", line 89, in _txtinfo_to_jsoninfo
    raise ParserError('Unrecognized format')
netdiff.exceptions.ParserError: Unrecognized format


I have send to you output jsoninfo from official olsrd version 0.9.0.3 via email

**Comment by nemesisdesign** [comment]
Try this:

```python
olsr = OlsrParser('http://127.0.0.1:9090')
```

And let me know.

**Comment by sp2ong** [comment]
Yes, now working OK,
Thank you very much.

Maybe this info put on 
https://github.com/ninuxorg/netdiff
in section:

Basic Usage Example

Calculate diff of an OLSR 0.6.x topology:

from netdiff import OlsrParser
from netdiff import diff

old = OlsrParser('./stored-olsr.json')
new = OlsrParser('telnet://127.0.0.1:9090')
diff(old, new)

In alternative, you may also use the subtraction operator:

from netdiff import OlsrParser
from netdiff import diff

old = OlsrParser('./stored-olsr.json')
new = OlsrParser('telnet://127.0.0.1:9090')
old - new

where examples show use telnet instead http

**Comment by nemesisdesign** [comment]
maybe better to put HTTP since it's working ok in most cases, could you send a patch to edit the README? That would be helpful because I can't do it right now (writing from mobile phone).

**Comment by sp2ong** [comment]
Federico,

I have send patch REDAME , please ignore my first patch because I have made mistake in name of protocol. The second patch is OK.

**Comment by nemesisdesign** [comment]
Ok it looks good, now create a *pull request* to this repository from the branch patch-2.

**Comment by nemesisdesign** [comment]
Don't worry I've pulled your change.
